name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: clang++ ttt.cpp -o text2table
    - name: Test
      run: ./test
    #- name: Linter
     # run: clang-tidy ttt.cpp
    - name: Linter (alt)
      uses: amcp-pit/cpp-linter@v1
